contact form
godybuoy/Portfolio-setup-and-mobile-first- pull request #3
Opened 2022-12-15 19:37 UTC by godybuoy

Add a contact form to finish first mobile setup

2022-12-15 20:10 UTC, mugishasam123 requested changes
Hi @godybuoy  👋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![alt](https://media.tenor.com/Pxh2kc7GmDoAAAAM/dog-so-close.gif)
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Descriptive PR title 👍 
- No linter errors 🥇 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-15 20:10 UTC, mugishasam123 commented on index.html
> +          <button class="start">get in touch</button>
- [ ] Kindly try to stick to the figma design as much as possible to make your project looks good. try to leverage padding colors etc.

Your design:
![image](https://user-images.githubusercontent.com/90524466/207955639-f27509ec-948a-4b86-a087-b1be4ccd751f.png)

Figma design:
![image](https://user-images.githubusercontent.com/90524466/207955821-9b5d352f-210b-48dc-8203-1c88021df718.png)

2022-12-15 20:10 UTC, mugishasam123 commented on index.html
> +          <input type="message" type="text" name="message" class="message" placeholder="write your message">
- [ ] Please try to implement all form features as it is stated in the project guidelines to make your project look professionally.(form validations like length,required etc)

2022-12-15 20:10 UTC, mugishasam123 commented on index.html
> +         <form class="form-start" action="">
- [ ] Please try to make your form functional by integrating with form spree service as it was stated in the project guidelines.

2022-12-16 15:37 UTC, godybuoy commented
I followed form spree services and implemented all form features

2022-12-16 15:38 UTC, merged

2022-12-16 16:23 UTC, emmiiorji reviewed
Hi @godybuoy, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

![Invalid](https://user-images.githubusercontent.com/20554583/208143336-95dc8975-708a-4d6a-b842-8f7278f7007b.gif)

You have submitted a pull request that has already been merged. It is required to not merge a pull request until it's approved, kindly undo the merge.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-16 16:53 UTC, godybuoy commented
@emmiiorji Hi! Thank you for your help. I made a merge and then submitted. should I unmerge or open a new pool request.

2022-12-16 18:51 UTC, joskalenda commented
> @emmiiorji Hi! Thank you for your help. I made a merge and then submitted. should I unmerge or open a new pool request.

Hey @godybuoy, I got your recent pull request submission, has said by this previous reviewer, you should not merge a pull request before it is approved, in case you do it, as you did with this one, please open a new one and add the link to the previous pull request in the newly created. << Please keep this in mind >>

⚠️  I will invalidate your new pull request because it does not have a descriptive pull request summary, please update it, and do not forget to add the merged pull request link for your future submission.